### ISSUE TITLE
no deforum tab and error on CMD window

### ISSUE THREAD

**Issue by agustincaniglia** [Rakile/DeforumationQT#1]
I am trying to install this, I don't understand if I should leave the original deforum extension installed. Either  way I don't get the Deforum tab on GUI.

Already up to date.
venv "F:\AI\Auto1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Requirement already satisfied: torch==2.1.2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (2.1.2+cu121)
Requirement already satisfied: torchvision==0.16.2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (0.16.2+cu121)
Requirement already satisfied: filelock in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (3.13.1)
Requirement already satisfied: sympy in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (1.12)
Requirement already satisfied: typing-extensions in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (4.9.0)
Requirement already satisfied: jinja2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (3.1.3)
Requirement already satisfied: fsspec in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (2024.2.0)
Requirement already satisfied: networkx in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (3.2.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torchvision==0.16.2) (9.5.0)
Requirement already satisfied: numpy in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torchvision==0.16.2) (1.26.2)
Requirement already satisfied: requests in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torchvision==0.16.2) (2.31.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from jinja2->torch==2.1.2) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision==0.16.2) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision==0.16.2) (2024.2.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision==0.16.2) (2.2.1)
Requirement already satisfied: idna<4,>=2.5 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision==0.16.2) (3.6)
Requirement already satisfied: mpmath>=0.19 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from sympy->torch==2.1.2) (1.3.0)

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: F:\AI\Auto1111\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Installing xformers
CUDA 12.1
Launching Web UI with arguments: --reinstall-torch --reinstall-xformers --xformers --no-half-vae --controlnet-dir D:/AUTOMATIC/WEBUI-forge/webui_forge_cu121_torch21/webui/models/ControlNet --ckpt-dir D:/AUTOMATIC/WEBUI-forge/webui_forge_cu121_torch21/webui/models/Stable-diffusion --vae-dir D:/AUTOMATIC/WEBUI-forge/webui_forge_cu121_torch21/webui/models/VAE --lora-dir D:/AUTOMATIC/WEBUI-forge/webui_forge_cu121_torch21/webui/models/Lora
[-] ADetailer initialized. version: 24.1.2, num models: 9
ControlNet preprocessor location: F:\AI\Auto1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-03-03 11:51:39,129 - ControlNet - INFO - ControlNet v1.1.440
2024-03-03 11:51:39,275 - ControlNet - INFO - ControlNet v1.1.440
[sd-webui-freeu] Controlnet support: *enabled*
11:51:39 - ReActor - STATUS - Running v0.7.0-a1 on Device: CUDA
Loading weights [fdbe56354b] from D:\AUTOMATIC\WEBUI-forge\webui_forge_cu121_torch21\webui\models\Stable-diffusion\dreamshaperXL_lightningDPMSDE.safetensors
2024-03-03 11:51:40,767 - AnimateDiff - INFO - Injecting LCM to UI.
2024-03-03 11:51:41,082 - AnimateDiff - INFO - Hacking i2i-batch.
2024-03-03 11:51:41,145 - ControlNet - INFO - ControlNet UI callback registered.
*Deforum ControlNet support: enabled*
*** Error executing callback ui_tabs_callback for F:\AI\Auto1111\stable-diffusion-webui\extensions\sd-webui-deforum\scripts\deforum.py
    Traceback (most recent call last):
      File "F:\AI\Auto1111\stable-diffusion-webui\modules\script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File "F:\AI\Auto1111\stable-diffusion-webui\extensions\sd-webui-deforum\scripts\deforum_helpers\ui_right.py", line 92, in on_ui_tabs
        deforum_gallery, generation_info, html_info, _ = create_output_panel("deforum", opts.outdir_img2img_samples)
    TypeError: cannot unpack non-iterable OutputPanel object

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: F:\AI\Auto1111\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Startup time: 28.3s (prepare environment: 13.3s, import torch: 4.8s, import gradio: 1.1s, setup paths: 2.3s, initialize shared: 0.2s, other imports: 0.6s, load scripts: 4.4s, create ui: 0.8s, gradio launch: 0.6s).
Applying attention optimization: xformers... done.
Model loaded in 8.2s (load weights from disk: 1.2s, create model: 1.8s, apply weights to model: 4.5s, move model to device: 0.2s, calculate empty prompt: 0.3s).
Saving backup of webui/extension state to F:\AI\Auto1111\stable-diffusion-webui\config_states\2024_03_03-11_55_28_Backup (pre-update).json.
Traceback (most recent call last):
  File "F:\AI\Auto1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\AI\Auto1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\AI\Auto1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\AI\Auto1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\AI\Auto1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\AI\Auto1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\AI\Auto1111\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\AI\Auto1111\stable-diffusion-webui\modules\ui_extensions.py", line 157, in extension_table
    ext.read_info_from_repo()
  File "F:\AI\Auto1111\stable-diffusion-webui\modules\extensions.py", line 112, in read_info_from_repo
    self.from_dict(d)
  File "F:\AI\Auto1111\stable-diffusion-webui\modules\extensions.py", line 95, in from_dict
    setattr(self, field, d[field])
TypeError: 'NoneType' object is not subscriptable
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Requirement already satisfied: torch==2.1.2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (2.1.2+cu121)
Requirement already satisfied: torchvision==0.16.2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (0.16.2+cu121)
Requirement already satisfied: jinja2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (3.1.3)
Requirement already satisfied: fsspec in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (2024.2.0)
Requirement already satisfied: typing-extensions in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (4.9.0)
Requirement already satisfied: filelock in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (3.13.1)
Requirement already satisfied: networkx in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (3.2.1)
Requirement already satisfied: sympy in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch==2.1.2) (1.12)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torchvision==0.16.2) (9.5.0)
Requirement already satisfied: numpy in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torchvision==0.16.2) (1.26.2)
Requirement already satisfied: requests in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torchvision==0.16.2) (2.31.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from jinja2->torch==2.1.2) (2.1.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision==0.16.2) (2.2.1)
Requirement already satisfied: idna<4,>=2.5 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision==0.16.2) (3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision==0.16.2) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests->torchvision==0.16.2) (2024.2.2)
Requirement already satisfied: mpmath>=0.19 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from sympy->torch==2.1.2) (1.3.0)

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: F:\AI\Auto1111\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Installing xformers
Collecting ultralytics>=8.1.18
  Downloading ultralytics-8.1.20-py3-none-any.whl (716 kB)
     ------------------------------------- 716.3/716.3 kB 11.4 MB/s eta 0:00:00
Requirement already satisfied: torch>=1.8.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (2.1.2+cu121)
Requirement already satisfied: psutil in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (5.9.5)
Requirement already satisfied: pandas>=1.1.4 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (2.2.0)
Requirement already satisfied: requests>=2.23.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (1.12.0)
Requirement already satisfied: matplotlib>=3.3.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (3.8.3)
Requirement already satisfied: opencv-python>=4.6.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (4.9.0.80)
Requirement already satisfied: seaborn>=0.11.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (0.13.2)
Requirement already satisfied: tqdm>=4.64.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (4.66.2)
Requirement already satisfied: torchvision>=0.9.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (0.16.2+cu121)
Requirement already satisfied: py-cpuinfo in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (9.0.0)
Requirement already satisfied: thop>=0.1.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (0.1.1.post2209072238)
Requirement already satisfied: pillow>=7.1.2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (9.5.0)
Requirement already satisfied: pyyaml>=5.3.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.1.18) (6.0.1)
Requirement already satisfied: fonttools>=4.22.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.1.18) (4.49.0)
Requirement already satisfied: kiwisolver>=1.3.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.1.18) (1.4.5)
Requirement already satisfied: packaging>=20.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.1.18) (23.2)
Requirement already satisfied: cycler>=0.10 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.1.18) (0.12.1)
Requirement already satisfied: numpy<2,>=1.21 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.1.18) (1.26.2)
Requirement already satisfied: pyparsing>=2.3.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.1.18) (3.1.1)
Requirement already satisfied: contourpy>=1.0.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.1.18) (1.2.0)
Requirement already satisfied: python-dateutil>=2.7 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.1.18) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from pandas>=1.1.4->ultralytics>=8.1.18) (2024.1)
Requirement already satisfied: pytz>=2020.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from pandas>=1.1.4->ultralytics>=8.1.18) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.1.18) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.1.18) (2024.2.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.1.18) (2.2.1)
Requirement already satisfied: idna<4,>=2.5 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.1.18) (3.6)
Requirement already satisfied: networkx in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.1.18) (3.2.1)
Requirement already satisfied: typing-extensions in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.1.18) (4.9.0)
Requirement already satisfied: filelock in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.1.18) (3.13.1)
Requirement already satisfied: jinja2 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.1.18) (3.1.3)
Requirement already satisfied: sympy in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.1.18) (1.12)
Requirement already satisfied: fsspec in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.1.18) (2024.2.0)
Requirement already satisfied: colorama in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from tqdm>=4.64.0->ultralytics>=8.1.18) (0.4.6)
Requirement already satisfied: six>=1.5 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics>=8.1.18) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics>=8.1.18) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in f:\ai\auto1111\stable-diffusion-webui\venv\lib\site-packages (from sympy->torch>=1.8.0->ultralytics>=8.1.18) (1.3.0)
Installing collected packages: ultralytics
  Attempting uninstall: ultralytics
    Found existing installation: ultralytics 8.1.16
    Uninstalling ultralytics-8.1.16:
      Successfully uninstalled ultralytics-8.1.16
Successfully installed ultralytics-8.1.20
CUDA 12.1
Launching Web UI with arguments: --reinstall-torch --reinstall-xformers --xformers --no-half-vae --controlnet-dir D:/AUTOMATIC/WEBUI-forge/webui_forge_cu121_torch21/webui/models/ControlNet --ckpt-dir D:/AUTOMATIC/WEBUI-forge/webui_forge_cu121_torch21/webui/models/Stable-diffusion --vae-dir D:/AUTOMATIC/WEBUI-forge/webui_forge_cu121_torch21/webui/models/VAE --lora-dir D:/AUTOMATIC/WEBUI-forge/webui_forge_cu121_torch21/webui/models/Lora
*** Error running preload() for F:\AI\Auto1111\stable-diffusion-webui\extensions\sd-webui-deforum\preload.py
    Traceback (most recent call last):
      File "F:\AI\Auto1111\stable-diffusion-webui\modules\script_loading.py", line 28, in preload_extensions
        module.preload(parser)
      File "F:\AI\Auto1111\stable-diffusion-webui\extensions\sd-webui-deforum\preload.py", line 19, in preload
        parser.add_argument(
      File "C:\Program Files\Python310\lib\argparse.py", line 1448, in add_argument
        return self._add_action(action)
      File "C:\Program Files\Python310\lib\argparse.py", line 1814, in _add_action
        self._optionals._add_action(action)
      File "C:\Program Files\Python310\lib\argparse.py", line 1650, in _add_action
        action = super(_ArgumentGroup, self)._add_action(action)
      File "C:\Program Files\Python310\lib\argparse.py", line 1462, in _add_action
        self._check_conflict(action)
      File "C:\Program Files\Python310\lib\argparse.py", line 1599, in _check_conflict
        conflict_handler(action, confl_optionals)
      File "C:\Program Files\Python310\lib\argparse.py", line 1608, in _handle_conflict_error
        raise ArgumentError(action, message % conflict_string)
    argparse.ArgumentError: argument --deforum-api: conflicting option string: --deforum-api

---
yolov8x-world.pt: 100%|█████████████████████████████████████████████████████████████| 148M/148M [00:03<00:00, 37.5MB/s]
[-] ADetailer initialized. version: 24.3.0, num models: 10
ControlNet preprocessor location: F:\AI\Auto1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-03-03 11:56:10,814 - ControlNet - INFO - ControlNet v1.1.441
2024-03-03 11:56:10,969 - ControlNet - INFO - ControlNet v1.1.441
[sd-webui-freeu] Controlnet support: *enabled*
11:56:11 - ReActor - STATUS - Running v0.7.0-b1 on Device: CUDA
Loading weights [fdbe56354b] from D:\AUTOMATIC\WEBUI-forge\webui_forge_cu121_torch21\webui\models\Stable-diffusion\dreamshaperXL_lightningDPMSDE.safetensors
2024-03-03 11:56:12,790 - ControlNet - INFO - ControlNet UI callback registered.
*Deforum ControlNet support: enabled*
*** Error executing callback ui_tabs_callback for F:\AI\Auto1111\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum.py
    Traceback (most recent call last):
      File "F:\AI\Auto1111\stable-diffusion-webui\modules\script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File "F:\AI\Auto1111\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\ui_right.py", line 92, in on_ui_tabs
        deforum_gallery, generation_info, html_info, _ = create_output_panel("deforum", opts.outdir_img2img_samples)
    TypeError: cannot unpack non-iterable OutputPanel object

---
*** Error executing callback ui_tabs_callback for F:\AI\Auto1111\stable-diffusion-webui\extensions\sd-webui-deforum\scripts\deforum.py
    Traceback (most recent call last):
      File "F:\AI\Auto1111\stable-diffusion-webui\modules\script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File "F:\AI\Auto1111\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\ui_right.py", line 92, in on_ui_tabs
        deforum_gallery, generation_info, html_info, _ = create_output_panel("deforum", opts.outdir_img2img_samples)
    TypeError: cannot unpack non-iterable OutputPanel object

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 36.3s (prepare environment: 17.2s, import torch: 4.6s, import gradio: 1.1s, setup paths: 2.1s, initialize shared: 0.2s, other imports: 0.6s, load scripts: 8.9s, create ui: 0.9s, gradio launch: 0.7s).
Creating model from config: F:\AI\Auto1111\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Applying attention optimization: xformers... done.
Model loaded in 7.4s (load weights from disk: 1.6s, create model: 0.8s, apply weights to model: 4.3s, move model to device: 0.1s, calculate empty prompt: 0.3s).

**Comment by lainollll** [comment]
This Automatic1111 problem Downgrade to 0.1.7
